import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import './globals.css'
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-zinc-900 text-zinc-50">
        {children}
      </body>
    </html>
  )
}
