const data = [
  {
    id: 1,
    role: 'Senior Full Stack Developer',
    company: 'bbox.digital',
    location: 'Remote',
    start: `${new Date('2021/12/01').toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
    end: 'Present',
    description:
      'Lead architecture and full-stack delivery across several client platforms in parallel — from spec and technical direction through implementation, release coordination, and production hardening. Build on React, Next.js, and TypeScript with Node.js, GraphQL/REST APIs, GCP/Firebase, and headless CMS architectures (Sanity, Squidex), including bilingual (FR/EN) routing and Algolia search backends (facets, sort replicas, InstantSearch). Modernized Cloud Functions to Gen2 on Node 22 with concurrency tuning for SSR performance, and migrated secrets off the deprecated functions.config() API to Secret Manager with dotenv for local development. Hardened production systems with resilient pipelines — exponential backoff, graceful degradation, and per-stage error observability — and a deployment-orchestration layer that unified promote and rollback into a single state machine. Standardized AI-assisted workflows across the portfolio, consolidating AGENTS.md as a single source of truth per repo and using Claude Code and GitHub Copilot to accelerate architecture, refactoring, and documentation. Optimization work improved CMS API efficiency by 100%, cut external API calls by 20%, and reduced Algolia search requests by ~95% (4.9M → 0.23M/month); CI/CD pipelines, automated testing (Jest, Playwright), and SEO/a11y work drove a 40% increase in Google Search impressions.',
    tools: [
      'React',
      'Next.js',
      'TypeScript',
      'Node.js',
      'GraphQL',
      'Firebase',
      'Google Cloud Platform',
      'Algolia',
      'CI/CD',
      'Playwright',
    ],
  },
  {
    id: 2,
    role: 'Webflow Expert / Web Developer / Web Designer',
    company: 'Upwork (Freelance)',
    location: 'Remote',
    start: `${new Date('2021/05/01').toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
    end: `${new Date('2021/12/01').toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
    description: 'Designed and developed responsive web applications using Figma, Webflow, and JavaScript. Delivered client projects with focus on clean UI/UX, scalability, and maintainability while ensuring clear communication and on-time delivery. Collaborated with clients in an agile environment to ensure product goals were achieved efficiently and iteratively.',
    tools: ['Webflow', 'Figma', 'JavaScript', 'UI/UX'],
  },
  {
    id: 3,
    role: 'Aviation Career',
    company: 'Porter Airlines | PAL Aerospace | Moncton Flight College',
    location: 'Various',
    start: '2013',
    end: '2021',
    description: 'Held leadership and training roles in commercial and medevac operations. Developed expertise in team coordination, precision under pressure, and regulatory compliance—skills directly transferable to software project leadership and reliability engineering.',
    tools: ['Leadership', 'Team Coordination', 'Project Management'],
  },
];
export default data;
