const data = [
  {
    id: 1,
    role: 'Senior Full Stack Developer',
    company: 'bbox.digital',
    location: 'Remote',
    start: `${new Date('2021/12/01').toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
    end: 'Present',
    description:
      'Responsible for planning, architecting, and delivering full-stack web applications across multiple client projects. Partnered closely with the company\'s co-founder to define technical direction and ensure scalable, maintainable solutions built on modern web and cloud technologies. Designed and developed scalable web applications using React, Next.js, TypeScript, and Tailwind CSS, aligning solutions with business and client goals. Architected and maintained cloud-based systems with Node.js, REST, and GraphQL APIs on GCP/Firebase, integrating headless CMS architectures to improve performance, maintainability, and scalability. Applied AI-assisted development tools (Claude Code, GitHub Copilot, Codex, GitHub Spec Kit) to accelerate architecture planning, refactoring, and documentation workflows. Developed and optimized caching strategies on GCP infrastructure, improving CMS API efficiency by 100%, reducing external API calls by 20%, and cutting Algolia search requests by ~95% (4.9M → 0.23M/month). Implemented CI/CD pipelines with GitHub Actions, ensuring smooth, reliable release processes. Enhanced code quality and reliability through automated testing (Jest for unit tests, Playwright for E2E). Designed and implemented database schemas using Firestore and PostgreSQL (Supabase), maintaining data integrity, access control, and scalability. Integrated Stripe SDKs for secure payment processing and subscription management. Ensured SEO-friendly and accessible (a11y) interfaces, improving Lighthouse performance and core web vitals, contributing to a 40% increase in Google Search Console impressions.',
    tools: [
      'React',
      'Next.js',
      'TypeScript',
      'JavaScript',
      'Node.js',
      'Tailwind CSS',
      'REST API',
      'GraphQL',
      'Firebase',
      'Firestore',
      'PostgreSQL',
      'Supabase',
      'Google Cloud Platform',
      'Cloud Run',
      'Pub/Sub',
      'Docker',
      'Headless CMS',
      'Stripe Payments',
      'GitHub Actions',
      'CI/CD',
      'Jest',
      'Playwright',
      'SEO',
      'a11y',
      'Claude Code',
      'GitHub Copilot',
      'Technical Documentation',
      'System Design',
      'API Design',
      'Microservices',
      'Agile Development',
      'Scrum',
    ],
  },
  {
    id: 2,
    role: 'Webflow Expert / Web Developer / Web Designer',
    company: 'Upwork (Freelance)',
    location: 'Remote',
    start: `${new Date('2021/05/01').toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
    end: `${new Date('2021/12/01').toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
    description: 'Designed and developed responsive web applications using Figma, Webflow, and JavaScript. Delivered client projects with focus on clean UI/UX, scalability, and maintainability while ensuring clear communication and on-time delivery. Collaborated with clients in an agile environment to ensure product goals were achieved efficiently and iteratively.',
    tools: ['Webflow', 'Figma', 'JavaScript', 'HTML', 'CSS', 'Responsive Web Design', 'UI/UX', 'SEO', 'Agile Development'],
  },
  {
    id: 3,
    role: 'Aviation Career',
    company: 'Porter Airlines | PAL Aerospace | Moncton Flight College',
    location: 'Various',
    start: '2013',
    end: '2021',
    description: 'Held leadership and training roles in commercial and medevac operations. Developed expertise in team coordination, precision under pressure, and regulatory compliance—skills directly transferable to software project leadership and reliability engineering.',
    tools: ['Leadership', 'Team Coordination', 'Training', 'Regulatory Compliance', 'Project Management'],
  },
];
export default data;
